#!/usr/bin/env python3
"""Create a disposable Unity test project containing the package and bridge sample."""

import argparse
import json
import os
import re
import shutil
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--unity", default="6000.6.0f1", help="Complete installed editor version")
    parser.add_argument("--urp", default="17.6.0", help="Exact URP package version")
    parser.add_argument("--output", type=Path, default=Path("Validation~/Project"))
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    if not re.fullmatch(r"6000\.(?:[6-9]|[1-9][0-9]+)\.[0-9]+[abfp][0-9]+", args.unity):
        parser.error("--unity must be a complete Unity 6.6-or-newer editor version")
    if not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+(?:-[A-Za-z0-9.]+)?", args.urp):
        parser.error("--urp must be an exact package version")
    root = args.repo.resolve()
    output = args.output.resolve()
    marker = output / ".grass-validation-project"
    if output == root or output in root.parents:
        parser.error("output cannot replace the repository or its parent")
    for source in (root / "Integrations~/MicroVerse", root / "Tools~/UnityProject"):
        source = source.resolve()
        if output == source or source in output.parents:
            parser.error("output cannot be inside a copied source directory")
    if output.exists() and not output.is_dir():
        parser.error("output must be a directory")
    if output.exists() and any(output.iterdir()) and not marker.is_file():
        parser.error("output contains unrelated files; choose a new directory")
    package = json.loads((root / "package.json").read_text())
    for directory in ("Assets", "Packages", "ProjectSettings"):
        (output / directory).mkdir(parents=True, exist_ok=True)
    marker.write_text("Generated by Tools~/create_validation_project.py\n")
    # Keep the UPM dependency relative to the project's Packages directory. The
    # project and package are mounted together by GameCI at a different container
    # path, so a host absolute file: dependency would break inside the container.
    relative_package = Path(os.path.relpath(root, output / "Packages")).as_posix()
    manifest = {
        "dependencies": {
            package["name"]: "file:" + relative_package,
            "com.unity.render-pipelines.universal": args.urp,
            "com.unity.test-framework": "1.6.0",
            # Terrain/Collider authoring and runtime diagnostics use these
            # built-in modules; URP does not enable them transitively.
            "com.unity.modules.imgui": "1.0.0",
            "com.unity.modules.physics": "1.0.0",
            "com.unity.modules.terrain": "1.0.0",
            "com.unity.modules.terrainphysics": "1.0.0",
            "com.unity.modules.jsonserialize": "1.0.0",
            "com.unity.modules.screencapture": "1.0.0",
            "com.unity.modules.imageconversion": "1.0.0",
        },
        "testables": [package["name"]],
    }
    (output / "Packages/manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (output / "ProjectSettings/ProjectVersion.txt").write_text(f"m_EditorVersion: {args.unity}\n")
    sample = output / "Assets/MicroVerseMaskBridge"
    if sample.exists():
        shutil.rmtree(sample)
    shutil.copytree(root / "Integrations~/MicroVerse", sample)
    for name in ("Editor", "Runtime"):
        source = root / "Tools~/UnityProject" / name
        destination = output / "Assets" / ("Editor" if name == "Editor" else "ValidationRuntime")
        if destination.exists():
            shutil.rmtree(destination)
        if source.is_dir():
            shutil.copytree(source, destination)
    print(f"Created {output} for Unity {args.unity}, URP {args.urp}.")
    print("Includes package EditMode tests and synthetic saved-mask bridge tests. Proprietary MicroVerse assemblies are not included.")
    print("GrassValidationBuild.BuildCurrent creates a real grass scene and clean/incremental standalone players; its optional smoke mode writes GPU results and captures.")


if __name__ == "__main__":
    main()
