#!/usr/bin/env python3
"""Create a disposable Unity test project containing the package and bridge sample."""

import argparse
import json
import os
import re
import shutil
from pathlib import Path


def remove_owned_path(path):
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    elif path.exists() or path.is_symlink():
        path.unlink()


def synchronize_templates(source, destination):
    """Replace owned sources without changing Unity identities of retained assets."""
    if not source.is_dir():
        remove_owned_path(destination)
        remove_owned_path(destination.with_name(destination.name + ".meta"))
        return
    if destination.is_symlink() or (destination.exists() and not destination.is_dir()):
        remove_owned_path(destination)
        remove_owned_path(destination.with_name(destination.name + ".meta"))
    destination.mkdir(parents=True, exist_ok=True)
    sources = {item.name: item for item in source.iterdir()}
    for item in destination.iterdir():
        # Unity creates metadata on import for templates that do not ship it.
        # Keep that metadata while its file/folder remains in the source tree;
        # saved scenes and renderer assets refer to the GUID it contains.
        if item.name in sources or (item.name.endswith(".meta") and item.name[:-5] in sources):
            continue
        remove_owned_path(item)
    # Copy metadata last so it remains authoritative even when an owned path
    # changes between a file and a folder during template replacement.
    for name, item in sorted(sources.items(), key=lambda pair: pair[0].endswith(".meta")):
        target = destination / name
        if item.is_dir():
            synchronize_templates(item, target)
        else:
            if target.is_symlink():
                target.unlink()
            if target.is_dir():
                remove_owned_path(target)
                remove_owned_path(target.with_name(target.name + ".meta"))
            # A source-provided .meta file deliberately replaces the old one.
            shutil.copy2(item, target)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--unity", default="6000.6.0f1", help="Complete installed editor version")
    parser.add_argument("--urp", default="17.6.0", help="Exact URP package version")
    parser.add_argument("--output", type=Path, default=Path("Validation~/Project"))
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    if not re.fullmatch(r"6000\.(?:[6-9]|[1-9][0-9]+)\.[0-9]+[abfp][0-9]+", args.unity):
        parser.error("--unity must be a complete Unity 6.6-or-newer editor version")
    if not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+(?:-[A-Za-z0-9.]+)?", args.urp):
        parser.error("--urp must be an exact package version")
    root = args.repo.resolve()
    output = args.output.resolve()
    marker = output / ".grass-validation-project"
    sample_source = root / "Integrations~/MicroVerse"
    template_source = root / "Tools~/UnityProject"
    # These three roots are required by the generated build harness. A partial
    # checkout must not be mistaken for deleted templates and erase scripts
    # whose GUIDs are still referenced by the existing validation scene.
    for source in (sample_source, template_source / "Editor", template_source / "Runtime"):
        if not source.is_dir():
            parser.error(f"required validation template directory is missing: {source}")
    if output == root or output in root.parents:
        parser.error("output cannot replace the repository or its parent")
    for source in (sample_source, template_source):
        source = source.resolve()
        if output == source or source in output.parents:
            parser.error("output cannot be inside a copied source directory")
    if output.exists() and not output.is_dir():
        parser.error("output must be a directory")
    if output.exists() and any(output.iterdir()) and not marker.is_file():
        parser.error("output contains unrelated files; choose a new directory")
    package = json.loads((root / "package.json").read_text())
    for directory in ("Assets", "Packages", "ProjectSettings"):
        (output / directory).mkdir(parents=True, exist_ok=True)
    marker.write_text("Generated by Tools~/create_validation_project.py\n")
    # Keep the UPM dependency relative to the project's Packages directory. The
    # project and package are mounted together by GameCI at a different container
    # path, so a host absolute file: dependency would break inside the container.
    relative_package = Path(os.path.relpath(root, output / "Packages")).as_posix()
    manifest = {
        "dependencies": {
            package["name"]: "file:" + relative_package,
            "com.unity.render-pipelines.universal": args.urp,
            "com.unity.test-framework": "1.6.0",
            # Terrain/Collider authoring and runtime diagnostics use these
            # built-in modules; URP does not enable them transitively.
            "com.unity.modules.imgui": "1.0.0",
            "com.unity.modules.physics": "1.0.0",
            "com.unity.modules.terrain": "1.0.0",
            "com.unity.modules.terrainphysics": "1.0.0",
            "com.unity.modules.jsonserialize": "1.0.0",
            "com.unity.modules.screencapture": "1.0.0",
            "com.unity.modules.imageconversion": "1.0.0",
        },
        "testables": [package["name"]],
    }
    (output / "Packages/manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    (output / "ProjectSettings/ProjectVersion.txt").write_text(f"m_EditorVersion: {args.unity}\n")
    sample = output / "Assets/MicroVerseMaskBridge"
    synchronize_templates(sample_source, sample)
    for name in ("Editor", "Runtime"):
        source = template_source / name
        destination = output / "Assets" / ("Editor" if name == "Editor" else "ValidationRuntime")
        synchronize_templates(source, destination)
    print(f"Created {output} for Unity {args.unity}, URP {args.urp}.")
    print("Includes package EditMode tests and synthetic saved-mask bridge tests. Proprietary MicroVerse assemblies are not included.")
    print("GrassValidationBuild.BuildCurrent creates a real grass scene and clean/incremental standalone players; its optional smoke mode writes GPU results and captures.")


if __name__ == "__main__":
    main()
